### ISSUE TITLE
have some in-app purchase sample code?

### ISSUE THREAD

**Issue by androidcn** [roop/AppStoreReceiptDecoder#1]
have some in-app purchase sample code?

**Comment by roop** [comment]
Please clarify what exactly you're looking for. You want IAP sample code that does what?

**Comment by androidcn** [comment]
https://developer.apple.com/library/ios/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html#//apple_ref/doc/uid/TP40010573-CH104-SW1

**Comment by androidcn** [comment]
yep i want some IAP Sample code receipt validate

**Comment by roop** [comment]
The link you sent deals with validating a receipt by using your own server. It applies for both paid-upfront app receipts and in-app purchase receipts.

No, I don't use that because I don't run my own server. So I don't have any sample code that does that.

**Comment by androidcn** [comment]
no that's local 
i don't want send to my server. i don't have Server.
Validating Receipts With the App Store locally

**Comment by roop** [comment]
The Apple documentation for [_Validating Receipts Locally_](https://developer.apple.com/library/ios/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateLocally.html) already has sample code in Objective-C for this. You will need to build OpenSSL for iOS and statically link to that for making that sample code work.

I don't want to share my code that does the complete receipt validation and in-app-purchase validation, because, as the documentation says:

> If multiple applications use the same code for performing validation, this common code
> signature can be targeted by tools that patch application binaries.

**Comment by androidcn** [comment]
what about this 
Validating Receipts With the App Store
https://developer.apple.com/library/ios/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html#//apple_ref/doc/uid/TP40010573-CH104-SW1

**Comment by roop** [comment]
What about that? This (_Validating Receipts With the App Store_) is the link you included in [your previous comment](#issuecomment-122637096), so please see [my reply to that](#issuecomment-122637577).
